[workspace]
members = ["projects/*"]
default-members = [
    "projects/sm-ast",
    "projects/sm-pest",
    "projects/sm-parser",
    "projects/sm-types",
]

[profile.release]
lto = true
opt-level = "s"